apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: sample-microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-pod
  template:
    metadata:
      name: apache-pod
      labels:
        name: apache-pod
        app: sample-microservice-app
    spec:
      containers:
        - name: apache
          image: diptajeet/microservice-kubernetes-demo-apache
          ports:
            - containerPort: 80
