apiVersion: v1
kind: Service
metadata:
  name: apache
  app: sample-microservice-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    name: apache-pod
    app: sample-microservice-app
