apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: sample-microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-microservice-app
  template:
    metadata:
      name: customer-pod
      labels:
        name: customer-pod
        app: sample-microservice-app
    spec:
      containers:
        - name: customer
          image: diptajeet/microservice-kubernetes-demo-customer
          ports:
            - containerPort: 8080
