apiVersion: v1
kind: Service
metadata:
  name: customer-service
  app: sample-microservice-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: customer-pod
    app: sample-microservice-app
