apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    name: order-service
    app: sample-microservice-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: order-pod
    app: sample-microservice-app
