apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: sample-microservice-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-microservice-app
  template:
    metadata:
      name: order-pod
      labels:
        name: order-pod
        app: sample-microservice-app
    spec:
      containers:
        - name: order
          image: diptajeet/microservice-kubernetes-demo-order
          ports:
            - containerPort: 8080
